### ISSUE TITLE
Parsing error when SASS variable is a URL

### ISSUE THREAD

**Issue by BenTangible** [TangibleInc/template-system#42]
Hi @eliot-akira, I imagine you'll be having lots of fun solving 4.0.0 bugs, so to help balance the load I've just found a bug that existed prior to 4.0.0. You're welcome! Hahah 😜

It's a pretty weird one but is easy to replicate. I have [this barebones template](https://loops-test-forum.instawp.xyz/wp-admin/post.php?post=397&action=edit):

_Template_
```html
<Set name=variable_name><Field url /></Set>

<div class=background>Hello world!</div>
```

_Style_
```css
.background {
  text-align: center;
  padding: 1em;
  border-radius: 0.5em;
  background-color: SlateBlue;
  color: LightGray;
}
```

And it's displaying as expected on [this page](https://loops-test-forum.instawp.xyz/image-url-in-style-tab/). However, if I change the variable to `Set sass=variable_name`, my style breaks. This only seems to happen when the contents of a sass variable are a URL, since if I use something like `Field title` instead of `Field url`, it works fine.
